### ISSUE TITLE
uuid as id

### ISSUE THREAD

**Issue by hercegyu** [feathersjs-ecosystem/feathers-memory#117]
Hello,

I added support for uuid as id can you give me rights to can push my branch, and then you take a look, and maybe include it in some new releases.

Many thanks

**Comment by daffl** [comment]
Thank you for the suggestion. Since it is possible already to use a custom id, I think we'll best keep this separate in a hook, similar to something like

```js
const addUUID = context {
  const { data, service } = context;

  context.data = {
    [service.id]: uuid.generate(),
    ...data
  }

  return context;
}

app.service('myservice').hooks({
  before: {
    create: [
      addUUID
    ]
  }
});
```

**Comment by hercegyu** [comment]
Hello, and first of all thank you for responding.
This solution was also my idea, and that part is really fine. Maybe, as you pointed out, even better (lib will not have a dependency on UUID lib).
One of the problems I can't fix was a type. I need to set some predefined data, and for that purpose use store in MemoryServiceOptions. In it, the key can only be number. So that needs to be changed.
In all places for key/id in lib you are using Id (type Id = number | string;). Only in MemoryServiceStore, key is number. Can we change this to:
`export type MemoryServiceStore = {
  [key in Id]: any;
};`

Many thanks.

**Comment by daffl** [comment]
Totally, that makes sense. A pull request would be welcome.

**Comment by hercegyu** [comment]
Maybe it's a stupid question, but constantly getting :
`Permission to feathersjs-ecosystem/feathers-memory.git denied to hercegyu`
Using ssh and right key.

**Comment by daffl** [comment]
If you want to make changes you would fork the repository and use the fork.
