### ISSUE TITLE
Best practice for $search

### ISSUE THREAD

**Issue by alex-bashkatov-ezlo** [feathersjs-ecosystem/feathers-memory#51]
Hi guys,
as I understand feathers-memory doesn't support LIKE or $regex to filter by string chunks, e.g. match David by 'da'.
What's a good solution to do a quick filtering, maybe after hook or smth else?

Thanks in advance

**Comment by eddyystop** [comment]
I like https://www.npmjs.com/package/sift

**Comment by alex-bashkatov-ezlo** [comment]
thanks. finally extended memory find method

`async find(params) {
    const { query } = params;
    const re = {};

    Object.keys(query).forEach(key => {
      const obj = query[key];
      if (Object.prototype.hasOwnProperty.call(obj, '$regex')) {
        // make query pass
        delete query[key];
        re[key] = Object.assign(obj, {
          $regex: new RegExp(obj.$regex),
        });
      }
    });

    const values = await super.find(params);
    if (isEmpty(re)) {
      return values;
    }
    
    return sift(re, values);
  }`

**Comment by daffl** [comment]
This is really neat @eddyystop! Depending on the file size, I'm wondering if we should just use that instead of our own filters.

**Comment by eddyystop** [comment]
Would `sift` be 100% compatible with what we have now?

I was thinking of adding sift as a last hook before  publishing v3.3.0.

**Comment by daffl** [comment]
If it is compatible with MongoDB's query syntax I think it should. I'll give it a try and see how it works but it would be nice having to maintain it ourselves.

**Comment by eddyystop** [comment]
I added the `sifter` result hook that uses `sift`.

**Comment by Mattchewone** [comment]
I have added `sift` as the default `matcher` in the PR - https://github.com/feathersjs/feathers-memory/pull/57

**Comment by daffl** [comment]
Yep, this is now supported thanks to @Mattchewone!
