### ISSUE TITLE
Why are all the data deleted after the server is rebooted?

### ISSUE THREAD

**Issue by shanematte** [feathersjs-ecosystem/feathers-memory#68]
`"feathers-memory": "^2.1.0"`

And where are the data stored? On disk or RAM?
Do feathers have redis support?

**Comment by daffl** [comment]
As the description says this is an in memory (=== RAM) store. For persistent storage you probably want to look at a different [database adapter](https://docs.feathersjs.com/api/databases/adapters.html) (the easiest to use would be NeDB which is also used in the [chat application](https://docs.feathersjs.com/guides/chat/readme.html)).

You can also implement any other database [in your own services](https://docs.feathersjs.com/guides/basics/services.html).
