### ISSUE TITLE
Use with create-react-app

### ISSUE THREAD

**Issue by saiichihashimoto** [feathersjs-ecosystem/feathers-memory#74]
### Steps to reproduce

Using [create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) with this module breaks the build.

I'm using `@feathers/client` rather than `@feathers/feathers` and, when I exclude this module, everything builds. With it, the build breaks.

### Expected behavior
The create-react-app build should not break.

### Actual behavior
It does break. :-P

<img width="1440" alt="screen shot 2018-06-11 at 1 31 36 pm" src="https://user-images.githubusercontent.com/2819256/41255651-12e91cd2-6d7c-11e8-8aff-c06fb7663363.png">

I tried the same thing as [was suggested by @daffl in feathers-localstorage](https://github.com/feathersjs-ecosystem/feathers-localstorage/issues/66#issuecomment-381258949) and got a very similar error. Maybe the fix is the same fix?

**Comment by daffl** [comment]
It needs the same change as in https://github.com/feathersjs-ecosystem/feathers-localstorage/pull/67 - then it should be possible to import `feathers-memory/dist/feathers-memory`.

**Comment by saiichihashimoto** [comment]
PR Ready!
