### ISSUE TITLE
Previously functional batch service no longer works when creating in-memory service

### ISSUE THREAD

**Issue by JulsRicketti** [feathersjs-ecosystem/feathers-memory#77]
This may be a very specific case, so my apologies if this cannot be appropriately explained.
### Steps to reproduce
I had a service that did a batch update. It took care of creating, updating and deleting multiple items. This was done through a service, by overriding the `update` service method.

On the client side, I'd simply do a `PUT` request with whatever parameters I needed, and it would all work flawlessly.

Now that I moved this to as an in-memory service to mock my server on my client app, it no longer works and I get the following error:

```
BadRequest: You can not replace multiple instances. Did you mean 'patch'?
    at new BadRequest (/path_to_my_app/node_modules/@feathersjs/errors/lib/index.js:86:17)
    at Object.update (/path_to_my_app/node_modules/feathers-memory/lib/index.js:129:29)
    at processHooks.call.then.hookObject (/path_to_my_app/node_modules/@feathersjs/feathers/lib/hooks.js:65:27)
    at <anonymous>
```

For the sake of testing, I tried to override my `update` method with nothing but a console.log so I can see what's going on, but it never reaches there and still gives me the same error as before. This is what my mocked code currently looks like:

```
  const batchUpdate = app.use('/batch_update', memory({
    id: '_id',
    startId: state.items.length + 1,
    store: itemsStore
  }))

  app.service('batch_update').update(() => {
    console.log('hereeeee')
  })
```

The call do that service is done using a fetch API. Not sure if relevant, but this is what it currently looks like:
```
export default function batchUpdate (batchUpdates) {
  return fetch(`${BASE_URL}/batch_update`, {
    method: 'PUT',
    body: batchUpdates
  })
}

```

### Expected behavior
At this point, just the request to go through and display `hereeeee` in the console.

### Actual behavior
The error stated above:

> BadRequest: You can not replace multiple instances. Did you mean 'patch'?

### System configuration

**Module versions** 
"@feathersjs/express": "1.2.3"
"@feathersjs/feathers": "3.1.7"
"feathers-memory": "2.1.3"

**NodeJS version**: v8.9.4

**Operating System**: MacOS High Sierra

**Browser Version**: Chrome Version 67.0.3396.99

**Comment by daffl** [comment]
There are probably several problems:

1. The callback in

```js
  app.service('batch_update').update(() => {
    console.log('hereeeee')
  })
```

Is no longer supported. `update` will return a promise, which should be used.

2. As mentioned in the [database adapter common API](https://docs.feathersjs.com/api/databases/common.html#adapterupdateid-data-params), `update` with an `id` of `null` is not supported by the pre-built adapters (because you probably never want to replace all items with the same data). As the error message says, `patch` should be used in that case. Both, `update` and `patch` will always need an `id` and `data` parameter.

**Comment by JulsRicketti** [comment]
Thanks for the help!
I also screwed up when overriding my `update` service with something unrelated, but ultimately now it has been solved.
